packages:
  - packages/*
  - packages/fontaine/playground
  - packages/fontless/docs
  - packages/fontless/examples/*

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
