shellEmulator: true

packages:
  - packages/*
  - packages/fontaine/playground
  - packages/fontless/docs
  - packages/fontless/examples/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - shadcn-docs-nuxt
  - simple-git-hooks
