name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠 Build project
        run: pnpm build

      - name: 🔠 Lint project
        run: pnpm lint

      - name: ✂️ Knip project
        run: pnpm test:knip

      - name: ⚙️ Check package engines
        run: pnpm test:versions

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠 Build project
        run: pnpm build

      - name: 💪 Test types
        run: pnpm test:types

      - name: 🧪 Test project
        run: pnpm test:unit --coverage

      - name: 🟩 Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: 🧪 Test fontless integration (prepare)
        run: pnpm -C packages/fontless exec playwright install chromium

      - name: 🧪 Test fontless integration
        run: pnpm -C packages/fontless test-e2e
